local map = vim.keymap.set

map({ "n", "v" }, "<Space>", "<Nop>", { silent = true })
map("n", "<Esc>", "<Cmd>nohlsearch<CR>", { desc = "Clear search highlight" })
map("n", "<C-s>", "<Cmd>write<CR>", { desc = "Save file" })
map({ "i", "x", "n", "s" }, "<C-s>", "<Cmd>write<CR><Esc>", { desc = "Save file" })
map("n", "]b", "<Cmd>bnext<CR>", { desc = "Next buffer" })
map("n", "[b", "<Cmd>bprevious<CR>", { desc = "Previous buffer" })
map("n", "<Leader>bd", function() require("utils.buffer").close() end, { desc = "Delete buffer" })
map("n", "<Leader>bD", "<Cmd>bdelete!<CR>", { desc = "Delete buffer (force)" })
map("n", "<Leader>e", "<Cmd>Neotree toggle reveal<CR>", { desc = "Explorer" })
map("n", "<Leader>ff", function() Snacks.picker.files() end, { desc = "Find files" })
map("n", "<Leader>fg", function() Snacks.picker.grep() end, { desc = "Find text" })
map("n", "<Leader>fb", function() Snacks.picker.buffers() end, { desc = "Find buffers" })
map("n", "<Leader>fr", function() Snacks.picker.recent() end, { desc = "Recent files" })
map("n", "<Leader>gg", function() Snacks.lazygit() end, { desc = "Lazygit" })
map("n", "<Leader>l", "<Cmd>Lazy<CR>", { desc = "Lazy" })
map("n", "<Leader>m", "<Cmd>Mason<CR>", { desc = "Mason" })
map("n", "<Leader>q", "<Cmd>confirm qall<CR>", { desc = "Quit" })
map("n", "<C-h>", "<C-w>h", { desc = "Window left" })
map("n", "<C-j>", "<C-w>j", { desc = "Window down" })
map("n", "<C-k>", "<C-w>k", { desc = "Window up" })
map("n", "<C-l>", "<C-w>l", { desc = "Window right" })
map("v", "<", "<gv", { desc = "Indent left" })
map("v", ">", ">gv", { desc = "Indent right" })
map("n", "<A-j>", "<Cmd>move .+1<CR>==", { desc = "Move line down" })
map("n", "<A-k>", "<Cmd>move .-2<CR>==", { desc = "Move line up" })
map("v", "<A-j>", ":move '>+1<CR>gv=gv", { desc = "Move selection down" })
map("v", "<A-k>", ":move '<-2<CR>gv=gv", { desc = "Move selection up" })
