vim.cmd "highlight clear"
if vim.fn.exists "syntax_on" == 1 then vim.cmd "syntax reset" end

vim.g.colors_name = "nier"
vim.g.nier_mode = vim.o.background

local palettes = {
  light = {
    base = "#d6cfb5",
    surface = "#cec6aa",
    surface_alt = "#c4bca1",
    current = "#ccc4a8",
    selection = "#b9af91",
    border = "#463f2e",
    text = "#332e23",
    text_soft = "#5d5643",
    muted = "#7a7358",
    faint = "#8b8266",
    red = "#6e2a2a",
    red_bright = "#89413f",
    green = "#5f6846",
    green_bright = "#74805a",
    yellow = "#876d35",
    yellow_bright = "#9a814c",
    blue = "#53666b",
    blue_bright = "#697d82",
    purple = "#70586a",
    purple_bright = "#876f80",
    cyan = "#4f6b67",
    cyan_bright = "#66817c",
    orange = "#8b5a3c",
    syntax_comment = "#665f49",
    syntax_constant = "#8b5a3c",
    syntax_string = "#425a32",
    syntax_identifier = "#332e23",
    syntax_function = "#2d5266",
    syntax_statement = "#5d3d62",
    syntax_label = "#77571f",
    syntax_operator = "#463f2e",
    syntax_preproc = "#6e2a2a",
    syntax_type = "#2d5266",
    syntax_special = "#77571f",
    brightest = "#eee7ce",
  },
  dark = {
    -- The light palette's foreground and background exchange roles here.
    base = "#332e23",
    surface = "#463f2e",
    surface_alt = "#5d5643",
    current = "#413b2d",
    selection = "#665f49",
    border = "#aaa081",
    text = "#d6cfb5",
    text_soft = "#cec6aa",
    muted = "#aaa081",
    faint = "#7a7358",
    red = "#c17c78",
    red_bright = "#d9958f",
    green = "#a6ad7b",
    green_bright = "#bdc690",
    yellow = "#c8aa69",
    yellow_bright = "#dfc17f",
    blue = "#8fa8ae",
    blue_bright = "#a9c1c6",
    purple = "#ab8fa5",
    purple_bright = "#c3a8bd",
    cyan = "#86aaa2",
    cyan_bright = "#9dc2ba",
    orange = "#c89978",
    syntax_comment = "#aaa081",
    syntax_constant = "#cec6aa",
    syntax_string = "#d6cfb5",
    syntax_identifier = "#d6cfb5",
    syntax_function = "#eee7ce",
    syntax_statement = "#c4bca1",
    syntax_label = "#aaa081",
    syntax_operator = "#d6cfb5",
    syntax_preproc = "#cec6aa",
    syntax_type = "#eee7ce",
    syntax_special = "#c4bca1",
    brightest = "#eee7ce",
  },
}

local c = palettes[vim.o.background == "dark" and "dark" or "light"]

local groups = {
  Normal = { fg = c.text, bg = c.base },
  NormalNC = { fg = c.text_soft, bg = c.base },
  NormalFloat = { fg = c.text, bg = c.surface },
  FloatBorder = { fg = c.border, bg = c.surface },
  FloatTitle = { fg = c.red, bg = c.surface, bold = true },
  ColorColumn = { bg = c.current },
  Conceal = { fg = c.muted },
  Cursor = { fg = c.base, bg = c.text },
  CursorColumn = { bg = c.current },
  CursorLine = { bg = c.current },
  CursorLineNr = { fg = c.red, bg = c.current, bold = true },
  LineNr = { fg = c.faint },
  Directory = { fg = c.blue, bold = true },
  EndOfBuffer = { fg = c.base },
  ErrorMsg = { fg = c.red, bold = true },
  Folded = { fg = c.muted, bg = c.surface },
  FoldColumn = { fg = c.muted, bg = c.base },
  IncSearch = { fg = c.base, bg = c.border, bold = true },
  CurSearch = { fg = c.base, bg = c.red, bold = true },
  Search = { fg = c.base, bg = c.red },
  MatchParen = { fg = c.red, bold = true, underline = true },
  ModeMsg = { fg = c.green, bold = true },
  MoreMsg = { fg = c.blue },
  NonText = { fg = c.faint },
  Pmenu = { fg = c.text, bg = c.surface },
  PmenuSel = { fg = c.base, bg = c.red, bold = true },
  PmenuSbar = { bg = c.surface_alt },
  PmenuThumb = { bg = c.red },
  Question = { fg = c.green, bold = true },
  QuickFixLine = { bg = c.selection, bold = true },
  SignColumn = { fg = c.muted, bg = c.base },
  SpecialKey = { fg = c.faint },
  SpellBad = { sp = c.red, undercurl = true },
  SpellCap = { sp = c.blue, undercurl = true },
  SpellLocal = { sp = c.cyan, undercurl = true },
  SpellRare = { sp = c.purple, undercurl = true },
  StatusLine = { fg = c.text, bg = c.surface_alt },
  StatusLineNC = { fg = c.faint, bg = c.surface },
  StatusNormal = { fg = c.base, bg = c.border, bold = true },
  StatusInsert = { fg = c.base, bg = c.green, bold = true },
  StatusVisual = { fg = c.base, bg = c.purple, bold = true },
  StatusReplace = { fg = c.base, bg = c.red, bold = true },
  StatusCommand = { fg = c.base, bg = c.yellow, bold = true },
  StatusTerminal = { fg = c.base, bg = c.cyan, bold = true },
  TabLine = { fg = c.faint, bg = c.surface },
  TabLineFill = { bg = c.surface },
  TabLineSel = { fg = c.base, bg = c.red, bold = true },
  Title = { fg = c.red, bold = true },
  VertSplit = { fg = c.border },
  WinSeparator = { fg = c.border },
  Visual = { bg = c.selection },
  WarningMsg = { fg = c.yellow, bold = true },
  Whitespace = { fg = c.faint },
  WildMenu = { fg = c.base, bg = c.red },

  Comment = { fg = c.syntax_comment, italic = true },
  Constant = { fg = c.syntax_constant },
  String = { fg = c.syntax_string },
  Character = { link = "String" },
  Number = { fg = c.syntax_constant },
  Boolean = { fg = c.syntax_constant, bold = true },
  Float = { link = "Number" },
  Identifier = { fg = c.syntax_identifier },
  Function = { fg = c.syntax_function, bold = true },
  Statement = { fg = c.syntax_statement, bold = true },
  Conditional = { link = "Statement" },
  Repeat = { link = "Statement" },
  Label = { fg = c.syntax_label },
  Operator = { fg = c.syntax_operator },
  Keyword = { link = "Statement" },
  Exception = { fg = c.syntax_preproc, bold = true },
  PreProc = { fg = c.syntax_preproc, bold = true },
  Include = { link = "PreProc" },
  Define = { link = "PreProc" },
  Macro = { fg = c.syntax_constant, bold = true },
  Type = { fg = c.syntax_type, bold = true },
  StorageClass = { fg = c.syntax_statement, bold = true },
  Structure = { link = "Type" },
  Typedef = { link = "Type" },
  Special = { fg = c.syntax_special },

  DiagnosticError = { fg = c.red },
  DiagnosticWarn = { fg = c.yellow },
  DiagnosticInfo = { fg = c.blue },
  DiagnosticHint = { fg = c.cyan },
  DiagnosticOk = { fg = c.green },
  DiagnosticUnderlineError = { sp = c.red, undercurl = true },
  DiagnosticUnderlineWarn = { sp = c.yellow, undercurl = true },
  DiagnosticUnderlineInfo = { sp = c.blue, undercurl = true },
  DiagnosticUnderlineHint = { sp = c.cyan, undercurl = true },

  DiffAdd = { fg = c.green, bg = c.current },
  DiffChange = { fg = c.yellow, bg = c.current },
  DiffDelete = { fg = c.red, bg = c.current },
  DiffText = { fg = c.blue, bg = c.selection, bold = true },
  GitSignsAdd = { fg = c.green },
  GitSignsChange = { fg = c.yellow },
  GitSignsDelete = { fg = c.red },

  ["@variable"] = { fg = c.syntax_identifier },
  ["@variable.builtin"] = { fg = c.syntax_preproc, bold = true },
  ["@variable.parameter"] = { fg = c.syntax_constant },
  ["@variable.member"] = { fg = c.syntax_preproc },
  ["@function"] = { link = "Function" },
  ["@function.call"] = { link = "Function" },
  ["@function.method"] = { link = "Function" },
  ["@function.method.call"] = { link = "Function" },
  ["@type"] = { link = "Type" },
  ["@type.builtin"] = { fg = c.syntax_statement, bold = true },
  ["@keyword"] = { link = "Keyword" },
  ["@keyword.type"] = { link = "Keyword" },
  ["@keyword.import"] = { fg = c.syntax_preproc, bold = true },
  ["@string"] = { link = "String" },
  ["@number"] = { link = "Number" },
  ["@boolean"] = { link = "Boolean" },
  ["@comment"] = { link = "Comment" },
  ["@markup.heading"] = { fg = c.red, bold = true },
  ["@markup.link"] = { fg = c.blue, underline = true },
  ["@markup.raw"] = { fg = c.green },

  SnacksDashboardHeader = { fg = c.text, bold = true },
  SnacksDashboardDesc = { fg = c.muted },
  SnacksDashboardKey = { fg = c.red, bold = true },
  SnacksDashboardIcon = { fg = c.yellow },
  SnacksDashboardFooter = { fg = c.muted, italic = true },
  SnacksPickerBorder = { fg = c.border, bg = c.surface },
  SnacksPickerTitle = { fg = c.red, bg = c.surface, bold = true },
  SnacksInputBorder = { fg = c.border, bg = c.surface },
  SnacksNotifierBorderInfo = { fg = c.blue, bg = c.surface },
  SnacksNotifierBorderWarn = { fg = c.yellow, bg = c.surface },
  SnacksNotifierBorderError = { fg = c.red, bg = c.surface },

  BlinkCmpMenu = { fg = c.text, bg = c.surface },
  BlinkCmpMenuBorder = { fg = c.border, bg = c.surface },
  BlinkCmpMenuSelection = { fg = c.base, bg = c.red, bold = true },
  BlinkCmpLabelMatch = { fg = c.red, bold = true },
  BlinkCmpDoc = { fg = c.text, bg = c.surface },
  BlinkCmpDocBorder = { fg = c.border, bg = c.surface },
  WhichKey = { fg = c.red },
  WhichKeyGroup = { fg = c.blue },
  WhichKeyDesc = { fg = c.text },
  NeoTreeNormal = { fg = c.text, bg = c.surface },
  NeoTreeNormalNC = { fg = c.text_soft, bg = c.surface },
  NeoTreeDirectoryName = { fg = c.blue },
  NeoTreeDirectoryIcon = { fg = c.blue },
  NeoTreeGitAdded = { fg = c.green },
  NeoTreeGitModified = { fg = c.yellow },
  NeoTreeGitDeleted = { fg = c.red },
  LazyNormal = { fg = c.text, bg = c.surface },
  MasonNormal = { fg = c.text, bg = c.surface },
}

for name, spec in pairs(groups) do
  vim.api.nvim_set_hl(0, name, spec)
end

vim.g.terminal_color_0 = c.border
vim.g.terminal_color_1 = c.red
vim.g.terminal_color_2 = c.green
vim.g.terminal_color_3 = c.yellow
vim.g.terminal_color_4 = c.blue
vim.g.terminal_color_5 = c.purple
vim.g.terminal_color_6 = c.cyan
vim.g.terminal_color_7 = c.surface_alt
vim.g.terminal_color_8 = c.muted
vim.g.terminal_color_9 = c.red_bright
vim.g.terminal_color_10 = c.green_bright
vim.g.terminal_color_11 = c.yellow_bright
vim.g.terminal_color_12 = c.blue_bright
vim.g.terminal_color_13 = c.purple_bright
vim.g.terminal_color_14 = c.cyan_bright
vim.g.terminal_color_15 = c.brightest
